### ISSUE TITLE
Missing .config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml

### ISSUE THREAD

**Issue by WhistleMaster** [brainfucksec/kali-dotfiles#1]
Hi !

Really great theme, thanks for the work ! It seems that your repo is missing the xfce4-panel config file (/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml). Would it be possible to get it ?

Thanks !

WM

**Comment by brainfucksec** [comment]
Thanks WhistleMaster, the required configuration file has been added.
